console.log(typeof 'hello')
console.log(typeof 12)
console.log(typeof 12.23434)
console.log(typeof 12e3)
console.log(typeof true)
console.log(typeof undefined)
console.log(typeof null)
console.log(typeof 10000000n)
console.log(typeof [1, 2, 3])
